### ISSUE TITLE
Desired way to contribute translations of these tutorials?

### ISSUE THREAD

**Issue by xavidp** [PPBDS/r4ds.tutorials#19]
Hi:

First of all, congratulations for this brave and awesome job you are doing with this book (version 2 now!) and the addition of tutorials linked to it.

I'm considering to add some translations in Spanish to tutorials available for the v1 of the book, taking profit of the previous work done already to translate to Spanish the first version of your book.  
https://github.com/cienciadedatos/r4ds

For the time being, and for my own needs in my organization (teaching others about using R for data management in local Public Administrations), I just placed some of the tutorials from the `learnr` package in a fork I made of the translation into Spanish of your book r4ds (1st ed). And I will go translating tutorials there, one by one (today I fisnihed the first one from those Rmd)
https://github.com/cienciadedatos/r4ds/compare/traduccion...xavidp:r4ds:traduccion

But what would be the desired way to translate the r4ds.tutorials in the future into other languages (for instance, Spanish)? I mean, what would be the desired way to expose/contribute/share those translations? 
I saw that the `learnr`package is internationalized already (as far as the UI of the tutorials is concerned). But what about the tutorial content?

Maybe you had already thought about that and planned some way to handle content translations?

Best

Xavier

**Comment by xavidp** [comment]
Hi again. 

Would this approach (suggested by the maintainer of  the `learnr` package) be an option?
https://github.com/rstudio/learnr/discussions/784#discussioncomment-5971629

Best

**Comment by davidkane9** [comment]
Apologies for the delay in responding.

First, to clarify, I have nothing to do with the R4DS book, although I agree that it is excellent! I, and some collaborators, am only responsible for this package of tutorials.

> what would be the desired way to expose/contribute/share those translations?

I don't know, but I am eager to work with you to make this possible!

I agree that we should probably follow whatever is the recommended approach from the nice people at learnr.

However, as you can see, the tutorials are a bit of a mess right now. So, I would not start to translate unless/untill we both think that the chapter is ready for such a translation.

I think that the Spreadsheets (chapter 21) is stable, if you want to start an experiment with that chapter to make sure things work.

**Comment by xavidp** [comment]
Thanks for the pointer (and general feedback & guidance)!: I'll do so. 
Best

**Comment by xavidp** [comment]
Btw, and FYI: Yesterday I did contribute some translation already of the tutorial in the tutorial.helpers package  itself ("Geting Started").
Maybe you can have a look there to play around with the approach similar to the one suggested by Garrick at learnr package:
https://github.com/PPBDS/tutorial.helpers/pull/6

**Comment by davidkane9** [comment]
@xavidp What is the best email to contact you? I am at dave.kane@gmail.com.

**Comment by xavidp** [comment]
Thanks Dave, I've already sent you an email from my main contact email
